# Generated by Django 6.0 on 2026-01-06 05:35

import django.db.models.deletion
import products.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default=products.models.generate_random_color, max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='product_images')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
                ('category', models.ManyToManyField(related_name='products', to='products.category')),
            ],
            options={
                'unique_together': {('name', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='variant_images')),
                ('is_active', models.BooleanField(default=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='products.presentation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='products.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'unique_together': {('product', 'presentation', 'size', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='ProductEquivalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('equivalent_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equivalent_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalents_as_target', to='products.productvariant')),
                ('source_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalents_as_source', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Product Equivalent',
                'verbose_name_plural': 'Product Equivalents',
                'unique_together': {('source_variant', 'equivalent_variant')},
            },
        ),
    ]
